"""initial_persistent_domain

Revision ID: 4a1d4bdf7e5a
Revises: 
Create Date: 2026-08-13 11:45:01.397335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a1d4bdf7e5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('before_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('tester_id', sa.String(length=64), nullable=True),
    sa.Column('lot_id', sa.String(length=64), nullable=True),
    sa.Column('wafer_id', sa.String(length=64), nullable=True),
    sa.Column('site_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor'], unique=False)
    op.create_index('ix_audit_logs_entity_id', 'audit_logs', ['entity_id'], unique=False)
    op.create_index('ix_audit_logs_entity_type', 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_lot_id'), 'audit_logs', ['lot_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_site_id'), 'audit_logs', ['site_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tester_id'), 'audit_logs', ['tester_id'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_wafer_id'), 'audit_logs', ['wafer_id'], unique=False)
    op.create_table('optimization_metrics',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('previous_value', sa.Float(), nullable=False),
    sa.Column('improvement', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('accent', sa.String(length=32), nullable=False),
    sa.Column('trend', sa.String(length=8), nullable=False),
    sa.Column('series', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_optimization_metrics_updated_at'), 'optimization_metrics', ['updated_at'], unique=False)
    op.create_table('telemetry_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('tester_id', sa.String(length=64), nullable=True),
    sa.Column('site_id', sa.String(length=64), nullable=True),
    sa.Column('lot_id', sa.String(length=64), nullable=True),
    sa.Column('wafer_id', sa.String(length=64), nullable=True),
    sa.Column('die_id', sa.String(length=64), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('log_tag', sa.String(length=16), nullable=False),
    sa.Column('log_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_telemetry_events_die_id', 'telemetry_events', ['die_id'], unique=False)
    op.create_index('ix_telemetry_events_event_type', 'telemetry_events', ['event_type'], unique=False)
    op.create_index('ix_telemetry_events_lot_id', 'telemetry_events', ['lot_id'], unique=False)
    op.create_index('ix_telemetry_events_sequence_number', 'telemetry_events', ['sequence_number'], unique=False)
    op.create_index('ix_telemetry_events_site_id', 'telemetry_events', ['site_id'], unique=False)
    op.create_index('ix_telemetry_events_tester_id', 'telemetry_events', ['tester_id'], unique=False)
    op.create_index('ix_telemetry_events_timestamp', 'telemetry_events', ['timestamp'], unique=False)
    op.create_index('ix_telemetry_events_wafer_id', 'telemetry_events', ['wafer_id'], unique=False)
    op.create_table('tester_sites',
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('fab', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_table('optimization_metric_history',
    sa.Column('history_id', sa.String(length=64), nullable=False),
    sa.Column('metric_id', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['optimization_metrics.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index('ix_opt_metric_hist_metric_id', 'optimization_metric_history', ['metric_id'], unique=False)
    op.create_index('ix_opt_metric_hist_timestamp', 'optimization_metric_history', ['timestamp'], unique=False)
    op.create_table('testers',
    sa.Column('tester_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=True),
    sa.Column('health_pct', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['tester_sites.site_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('tester_id')
    )
    op.create_index('ix_testers_site_id', 'testers', ['site_id'], unique=False)
    op.create_table('lots',
    sa.Column('lot_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tester_id', sa.String(length=64), nullable=True),
    sa.Column('site_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_time_saved_hours', sa.Float(), nullable=False),
    sa.Column('overall_yield_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['tester_sites.site_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.tester_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('lot_id')
    )
    op.create_index('ix_lots_site_id', 'lots', ['site_id'], unique=False)
    op.create_index('ix_lots_started_at', 'lots', ['started_at'], unique=False)
    op.create_index('ix_lots_tester_id', 'lots', ['tester_id'], unique=False)
    op.create_table('maintenance_history',
    sa.Column('history_id', sa.String(length=64), nullable=False),
    sa.Column('tester_id', sa.String(length=64), nullable=False),
    sa.Column('component', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.tester_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index('ix_maint_hist_created_at', 'maintenance_history', ['created_at'], unique=False)
    op.create_index('ix_maint_hist_tester_id', 'maintenance_history', ['tester_id'], unique=False)
    op.create_table('maintenance_predictions',
    sa.Column('prediction_id', sa.String(length=64), nullable=False),
    sa.Column('tester_id', sa.String(length=64), nullable=False),
    sa.Column('component', sa.String(length=128), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('failure_probability', sa.Float(), nullable=True),
    sa.Column('rul_days', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('recommendation_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('model_available', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('features_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.tester_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index('ix_maint_pred_created_at', 'maintenance_predictions', ['created_at'], unique=False)
    op.create_index('ix_maint_pred_severity', 'maintenance_predictions', ['severity'], unique=False)
    op.create_index('ix_maint_pred_tester_id', 'maintenance_predictions', ['tester_id'], unique=False)
    op.create_table('predictive_maintenance',
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('tester_id', sa.String(length=64), nullable=True),
    sa.Column('site_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('component', sa.String(length=128), nullable=True),
    sa.Column('health_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rul_days', sa.Float(), nullable=True),
    sa.Column('failure_probability', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('model_available', sa.Boolean(), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['tester_sites.site_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.tester_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index('ix_pm_severity', 'predictive_maintenance', ['severity'], unique=False)
    op.create_index('ix_pm_tester_id', 'predictive_maintenance', ['tester_id'], unique=False)
    op.create_index('ix_pm_updated_at', 'predictive_maintenance', ['updated_at'], unique=False)
    op.create_table('telemetry_features',
    sa.Column('feature_id', sa.String(length=64), nullable=False),
    sa.Column('tester_id', sa.String(length=64), nullable=False),
    sa.Column('component', sa.String(length=128), nullable=False),
    sa.Column('test_failures', sa.Float(), nullable=False),
    sa.Column('parametric_drift', sa.Float(), nullable=False),
    sa.Column('contact_resistance', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('voltage_deviation', sa.Float(), nullable=False),
    sa.Column('current_deviation', sa.Float(), nullable=False),
    sa.Column('cycle_count', sa.Float(), nullable=False),
    sa.Column('historical_failures', sa.Float(), nullable=False),
    sa.Column('maintenance_events', sa.Float(), nullable=False),
    sa.Column('tester_utilization', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.tester_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feature_id')
    )
    op.create_index('ix_telemetry_features_captured_at', 'telemetry_features', ['captured_at'], unique=False)
    op.create_index('ix_telemetry_features_tester_id', 'telemetry_features', ['tester_id'], unique=False)
    op.create_table('dynamic_test_limits',
    sa.Column('limit_id', sa.String(length=64), nullable=False),
    sa.Column('parameter', sa.String(length=128), nullable=False),
    sa.Column('test_name', sa.String(length=128), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=True),
    sa.Column('tester_id', sa.String(length=64), nullable=True),
    sa.Column('lot_id', sa.String(length=64), nullable=True),
    sa.Column('previous_limit', sa.Float(), nullable=False),
    sa.Column('current_limit', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('change_percentage', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('cpk', sa.Float(), nullable=True),
    sa.Column('target_cpk', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_upper_limit', sa.Boolean(), nullable=False),
    sa.Column('lsl', sa.Float(), nullable=True),
    sa.Column('usl', sa.Float(), nullable=True),
    sa.Column('sample_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('active_adjustment_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['tester_sites.site_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.tester_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('limit_id')
    )
    op.create_index('ix_dtl_lot_id', 'dynamic_test_limits', ['lot_id'], unique=False)
    op.create_index('ix_dtl_site_id', 'dynamic_test_limits', ['site_id'], unique=False)
    op.create_index('ix_dtl_status', 'dynamic_test_limits', ['status'], unique=False)
    op.create_index('ix_dtl_tester_id', 'dynamic_test_limits', ['tester_id'], unique=False)
    op.create_index('ix_dtl_updated_at', 'dynamic_test_limits', ['updated_at'], unique=False)
    op.create_table('wafers',
    sa.Column('wafer_id', sa.String(length=64), nullable=False),
    sa.Column('lot_id', sa.String(length=64), nullable=False),
    sa.Column('tester_id', sa.String(length=64), nullable=True),
    sa.Column('site_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('yield_pct', sa.Float(), nullable=False),
    sa.Column('total_dies', sa.Integer(), nullable=False),
    sa.Column('tested_dies', sa.Integer(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('retest_count', sa.Integer(), nullable=False),
    sa.Column('reclass_count', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=128), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['tester_sites.site_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.tester_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('wafer_id')
    )
    op.create_index('ix_wafers_lot_id', 'wafers', ['lot_id'], unique=False)
    op.create_index('ix_wafers_tester_id', 'wafers', ['tester_id'], unique=False)
    op.create_index('ix_wafers_updated_at', 'wafers', ['updated_at'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tester_id', sa.String(length=64), nullable=True),
    sa.Column('site_id', sa.String(length=64), nullable=True),
    sa.Column('lot_id', sa.String(length=64), nullable=True),
    sa.Column('wafer_id', sa.String(length=64), nullable=True),
    sa.Column('source_event_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=128), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['tester_sites.site_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.tester_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wafer_id'], ['wafers.wafer_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('ix_alerts_lot_id', 'alerts', ['lot_id'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_site_id', 'alerts', ['site_id'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_tester_id', 'alerts', ['tester_id'], unique=False)
    op.create_index('ix_alerts_timestamp', 'alerts', ['timestamp'], unique=False)
    op.create_index('ix_alerts_wafer_id', 'alerts', ['wafer_id'], unique=False)
    op.create_table('dashboard_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lots_in_test', sa.Integer(), nullable=False),
    sa.Column('test_time_saved_hours', sa.Float(), nullable=False),
    sa.Column('overall_yield_pct', sa.Float(), nullable=False),
    sa.Column('active_wafer_id', sa.String(length=64), nullable=True),
    sa.Column('adjustments_today', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_wafer_id'], ['wafers.wafer_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dies',
    sa.Column('die_id', sa.String(length=64), nullable=False),
    sa.Column('wafer_id', sa.String(length=64), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('bin', sa.String(length=16), nullable=False),
    sa.Column('fail_code', sa.String(length=64), nullable=True),
    sa.Column('test_time_ms', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wafer_id'], ['wafers.wafer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('die_id'),
    sa.UniqueConstraint('wafer_id', 'x', 'y', name='uq_die_coord')
    )
    op.create_index(op.f('ix_dies_tested_at'), 'dies', ['tested_at'], unique=False)
    op.create_index('ix_dies_wafer_id', 'dies', ['wafer_id'], unique=False)
    op.create_table('limit_adjustments',
    sa.Column('adjustment_id', sa.String(length=64), nullable=False),
    sa.Column('limit_id', sa.String(length=64), nullable=False),
    sa.Column('previous_limit', sa.Float(), nullable=False),
    sa.Column('proposed_limit', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('change_percentage', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('cpk', sa.Float(), nullable=True),
    sa.Column('target_cpk', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['limit_id'], ['dynamic_test_limits.limit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('adjustment_id')
    )
    op.create_index('ix_limit_adj_created_at', 'limit_adjustments', ['created_at'], unique=False)
    op.create_index('ix_limit_adj_limit_id', 'limit_adjustments', ['limit_id'], unique=False)
    op.create_index(op.f('ix_limit_adjustments_status'), 'limit_adjustments', ['status'], unique=False)
    op.create_table('limit_approvals',
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('limit_id', sa.String(length=64), nullable=False),
    sa.Column('adjustment_id', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['limit_id'], ['dynamic_test_limits.limit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_limit_approvals_adjustment_id'), 'limit_approvals', ['adjustment_id'], unique=False)
    op.create_index(op.f('ix_limit_approvals_decided_at'), 'limit_approvals', ['decided_at'], unique=False)
    op.create_index(op.f('ix_limit_approvals_limit_id'), 'limit_approvals', ['limit_id'], unique=False)
    op.create_table('limit_audits',
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('limit_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('before_status', sa.String(length=32), nullable=True),
    sa.Column('after_status', sa.String(length=32), nullable=True),
    sa.Column('before_limit', sa.Float(), nullable=True),
    sa.Column('after_limit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['limit_id'], ['dynamic_test_limits.limit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_limit_audits_created_at'), 'limit_audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_limit_audits_limit_id'), 'limit_audits', ['limit_id'], unique=False)
    op.create_table('pattern_optimization_results',
    sa.Column('result_id', sa.String(length=64), nullable=False),
    sa.Column('lot_id', sa.String(length=64), nullable=True),
    sa.Column('wafer_id', sa.String(length=64), nullable=True),
    sa.Column('tester_id', sa.String(length=64), nullable=True),
    sa.Column('pattern_group', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('footprint_reduction_pct', sa.Float(), nullable=True),
    sa.Column('test_time_reduction_pct', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.tester_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wafer_id'], ['wafers.wafer_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index('ix_pattern_opt_created_at', 'pattern_optimization_results', ['created_at'], unique=False)
    op.create_index('ix_pattern_opt_lot_id', 'pattern_optimization_results', ['lot_id'], unique=False)
    op.create_index('ix_pattern_opt_tester_id', 'pattern_optimization_results', ['tester_id'], unique=False)
    op.create_index('ix_pattern_opt_wafer_id', 'pattern_optimization_results', ['wafer_id'], unique=False)
    op.create_table('test_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('tester_id', sa.String(length=64), nullable=True),
    sa.Column('site_id', sa.String(length=64), nullable=True),
    sa.Column('lot_id', sa.String(length=64), nullable=True),
    sa.Column('wafer_id', sa.String(length=64), nullable=True),
    sa.Column('die_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=128), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['tester_sites.site_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.tester_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wafer_id'], ['wafers.wafer_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_test_events_acknowledged', 'test_events', ['acknowledged'], unique=False)
    op.create_index(op.f('ix_test_events_die_id'), 'test_events', ['die_id'], unique=False)
    op.create_index('ix_test_events_event_type', 'test_events', ['event_type'], unique=False)
    op.create_index('ix_test_events_lot_id', 'test_events', ['lot_id'], unique=False)
    op.create_index('ix_test_events_sequence_number', 'test_events', ['sequence_number'], unique=False)
    op.create_index('ix_test_events_severity', 'test_events', ['severity'], unique=False)
    op.create_index('ix_test_events_site_id', 'test_events', ['site_id'], unique=False)
    op.create_index('ix_test_events_tester_id', 'test_events', ['tester_id'], unique=False)
    op.create_index('ix_test_events_timestamp', 'test_events', ['timestamp'], unique=False)
    op.create_index('ix_test_events_wafer_id', 'test_events', ['wafer_id'], unique=False)
    op.create_table('test_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('lot_id', sa.String(length=64), nullable=True),
    sa.Column('wafer_id', sa.String(length=64), nullable=True),
    sa.Column('tester_id', sa.String(length=64), nullable=True),
    sa.Column('site_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dies_tested', sa.Integer(), nullable=False),
    sa.Column('yield_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['tester_sites.site_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.tester_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wafer_id'], ['wafers.wafer_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('ix_test_runs_lot_id', 'test_runs', ['lot_id'], unique=False)
    op.create_index('ix_test_runs_site_id', 'test_runs', ['site_id'], unique=False)
    op.create_index('ix_test_runs_started_at', 'test_runs', ['started_at'], unique=False)
    op.create_index('ix_test_runs_tester_id', 'test_runs', ['tester_id'], unique=False)
    op.create_index('ix_test_runs_wafer_id', 'test_runs', ['wafer_id'], unique=False)
    op.create_table('wafer_metrics',
    sa.Column('metric_id', sa.String(length=64), nullable=False),
    sa.Column('wafer_id', sa.String(length=64), nullable=False),
    sa.Column('lot_id', sa.String(length=64), nullable=True),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wafer_id'], ['wafers.wafer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index('ix_wafer_metrics_lot_id', 'wafer_metrics', ['lot_id'], unique=False)
    op.create_index('ix_wafer_metrics_metric_key', 'wafer_metrics', ['metric_key'], unique=False)
    op.create_index('ix_wafer_metrics_timestamp', 'wafer_metrics', ['timestamp'], unique=False)
    op.create_index('ix_wafer_metrics_wafer_id', 'wafer_metrics', ['wafer_id'], unique=False)
    op.create_table('die_test_results',
    sa.Column('result_id', sa.String(length=64), nullable=False),
    sa.Column('die_id', sa.String(length=64), nullable=False),
    sa.Column('wafer_id', sa.String(length=64), nullable=False),
    sa.Column('lot_id', sa.String(length=64), nullable=True),
    sa.Column('tester_id', sa.String(length=64), nullable=True),
    sa.Column('site_id', sa.String(length=64), nullable=True),
    sa.Column('test_run_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('fail_code', sa.String(length=64), nullable=True),
    sa.Column('test_time_ms', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['die_id'], ['dies.die_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['tester_sites.site_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.run_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.tester_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wafer_id'], ['wafers.wafer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index('ix_die_test_results_die_id', 'die_test_results', ['die_id'], unique=False)
    op.create_index('ix_die_test_results_lot_id', 'die_test_results', ['lot_id'], unique=False)
    op.create_index('ix_die_test_results_tester_id', 'die_test_results', ['tester_id'], unique=False)
    op.create_index('ix_die_test_results_timestamp', 'die_test_results', ['timestamp'], unique=False)
    op.create_index('ix_die_test_results_wafer_id', 'die_test_results', ['wafer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_die_test_results_wafer_id', table_name='die_test_results')
    op.drop_index('ix_die_test_results_timestamp', table_name='die_test_results')
    op.drop_index('ix_die_test_results_tester_id', table_name='die_test_results')
    op.drop_index('ix_die_test_results_lot_id', table_name='die_test_results')
    op.drop_index('ix_die_test_results_die_id', table_name='die_test_results')
    op.drop_table('die_test_results')
    op.drop_index('ix_wafer_metrics_wafer_id', table_name='wafer_metrics')
    op.drop_index('ix_wafer_metrics_timestamp', table_name='wafer_metrics')
    op.drop_index('ix_wafer_metrics_metric_key', table_name='wafer_metrics')
    op.drop_index('ix_wafer_metrics_lot_id', table_name='wafer_metrics')
    op.drop_table('wafer_metrics')
    op.drop_index('ix_test_runs_wafer_id', table_name='test_runs')
    op.drop_index('ix_test_runs_tester_id', table_name='test_runs')
    op.drop_index('ix_test_runs_started_at', table_name='test_runs')
    op.drop_index('ix_test_runs_site_id', table_name='test_runs')
    op.drop_index('ix_test_runs_lot_id', table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index('ix_test_events_wafer_id', table_name='test_events')
    op.drop_index('ix_test_events_timestamp', table_name='test_events')
    op.drop_index('ix_test_events_tester_id', table_name='test_events')
    op.drop_index('ix_test_events_site_id', table_name='test_events')
    op.drop_index('ix_test_events_severity', table_name='test_events')
    op.drop_index('ix_test_events_sequence_number', table_name='test_events')
    op.drop_index('ix_test_events_lot_id', table_name='test_events')
    op.drop_index('ix_test_events_event_type', table_name='test_events')
    op.drop_index(op.f('ix_test_events_die_id'), table_name='test_events')
    op.drop_index('ix_test_events_acknowledged', table_name='test_events')
    op.drop_table('test_events')
    op.drop_index('ix_pattern_opt_wafer_id', table_name='pattern_optimization_results')
    op.drop_index('ix_pattern_opt_tester_id', table_name='pattern_optimization_results')
    op.drop_index('ix_pattern_opt_lot_id', table_name='pattern_optimization_results')
    op.drop_index('ix_pattern_opt_created_at', table_name='pattern_optimization_results')
    op.drop_table('pattern_optimization_results')
    op.drop_index(op.f('ix_limit_audits_limit_id'), table_name='limit_audits')
    op.drop_index(op.f('ix_limit_audits_created_at'), table_name='limit_audits')
    op.drop_table('limit_audits')
    op.drop_index(op.f('ix_limit_approvals_limit_id'), table_name='limit_approvals')
    op.drop_index(op.f('ix_limit_approvals_decided_at'), table_name='limit_approvals')
    op.drop_index(op.f('ix_limit_approvals_adjustment_id'), table_name='limit_approvals')
    op.drop_table('limit_approvals')
    op.drop_index(op.f('ix_limit_adjustments_status'), table_name='limit_adjustments')
    op.drop_index('ix_limit_adj_limit_id', table_name='limit_adjustments')
    op.drop_index('ix_limit_adj_created_at', table_name='limit_adjustments')
    op.drop_table('limit_adjustments')
    op.drop_index('ix_dies_wafer_id', table_name='dies')
    op.drop_index(op.f('ix_dies_tested_at'), table_name='dies')
    op.drop_table('dies')
    op.drop_table('dashboard_state')
    op.drop_index('ix_alerts_wafer_id', table_name='alerts')
    op.drop_index('ix_alerts_timestamp', table_name='alerts')
    op.drop_index('ix_alerts_tester_id', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_site_id', table_name='alerts')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_lot_id', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_wafers_updated_at', table_name='wafers')
    op.drop_index('ix_wafers_tester_id', table_name='wafers')
    op.drop_index('ix_wafers_lot_id', table_name='wafers')
    op.drop_table('wafers')
    op.drop_index('ix_dtl_updated_at', table_name='dynamic_test_limits')
    op.drop_index('ix_dtl_tester_id', table_name='dynamic_test_limits')
    op.drop_index('ix_dtl_status', table_name='dynamic_test_limits')
    op.drop_index('ix_dtl_site_id', table_name='dynamic_test_limits')
    op.drop_index('ix_dtl_lot_id', table_name='dynamic_test_limits')
    op.drop_table('dynamic_test_limits')
    op.drop_index('ix_telemetry_features_tester_id', table_name='telemetry_features')
    op.drop_index('ix_telemetry_features_captured_at', table_name='telemetry_features')
    op.drop_table('telemetry_features')
    op.drop_index('ix_pm_updated_at', table_name='predictive_maintenance')
    op.drop_index('ix_pm_tester_id', table_name='predictive_maintenance')
    op.drop_index('ix_pm_severity', table_name='predictive_maintenance')
    op.drop_table('predictive_maintenance')
    op.drop_index('ix_maint_pred_tester_id', table_name='maintenance_predictions')
    op.drop_index('ix_maint_pred_severity', table_name='maintenance_predictions')
    op.drop_index('ix_maint_pred_created_at', table_name='maintenance_predictions')
    op.drop_table('maintenance_predictions')
    op.drop_index('ix_maint_hist_tester_id', table_name='maintenance_history')
    op.drop_index('ix_maint_hist_created_at', table_name='maintenance_history')
    op.drop_table('maintenance_history')
    op.drop_index('ix_lots_tester_id', table_name='lots')
    op.drop_index('ix_lots_started_at', table_name='lots')
    op.drop_index('ix_lots_site_id', table_name='lots')
    op.drop_table('lots')
    op.drop_index('ix_testers_site_id', table_name='testers')
    op.drop_table('testers')
    op.drop_index('ix_opt_metric_hist_timestamp', table_name='optimization_metric_history')
    op.drop_index('ix_opt_metric_hist_metric_id', table_name='optimization_metric_history')
    op.drop_table('optimization_metric_history')
    op.drop_table('tester_sites')
    op.drop_index('ix_telemetry_events_wafer_id', table_name='telemetry_events')
    op.drop_index('ix_telemetry_events_timestamp', table_name='telemetry_events')
    op.drop_index('ix_telemetry_events_tester_id', table_name='telemetry_events')
    op.drop_index('ix_telemetry_events_site_id', table_name='telemetry_events')
    op.drop_index('ix_telemetry_events_sequence_number', table_name='telemetry_events')
    op.drop_index('ix_telemetry_events_lot_id', table_name='telemetry_events')
    op.drop_index('ix_telemetry_events_event_type', table_name='telemetry_events')
    op.drop_index('ix_telemetry_events_die_id', table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index(op.f('ix_optimization_metrics_updated_at'), table_name='optimization_metrics')
    op.drop_table('optimization_metrics')
    op.drop_index(op.f('ix_audit_logs_wafer_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tester_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_site_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_lot_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
